name: 'Get Branch Name'
description: 'Extracts the branch name from the ref'
outputs:
  branch:
    value: ${{ steps.extract.outputs.BRANCH_NAME }}
    description: 'The branch name'
runs:
  using: "composite"
  steps:
      - name: Extract branch name
        id: extract
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          fi
      - name: Print branch name
        run: echo "Branch name is ${{ steps.extract_branch.outputs.BRANCH_NAME }}"
        shell: bash