// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file pb/enums.proto (package stredono, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum stredono.Currency
 */
export enum Currency {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: PLN = 1;
   */
  PLN = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(Currency)
proto3.util.setEnumType(Currency, "stredono.Currency", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "PLN" },
]);

/**
 * @generated from enum stredono.Tier
 */
export enum Tier {
  /**
   * @generated from enum value: BASIC = 0;
   */
  BASIC = 0,

  /**
   * @generated from enum value: PLUS = 1;
   */
  PLUS = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(Tier)
proto3.util.setEnumType(Tier, "stredono.Tier", [
  { no: 0, name: "BASIC" },
  { no: 1, name: "PLUS" },
]);

/**
 * @generated from enum stredono.AuthLevel
 */
export enum AuthLevel {
  /**
   * @generated from enum value: NONE = 0;
   */
  NONE = 0,

  /**
   * @generated from enum value: EMAIL = 1;
   */
  EMAIL = 1,

  /**
   * @generated from enum value: OIDC = 2;
   */
  OIDC = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(AuthLevel)
proto3.util.setEnumType(AuthLevel, "stredono.AuthLevel", [
  { no: 0, name: "NONE" },
  { no: 1, name: "EMAIL" },
  { no: 2, name: "OIDC" },
]);

