name: 'Terraform Plan and Apply'
description: 'Run terraform plan and apply'
inputs:
  dir:
    description: 'The directory where the terraform files are located'
    required: true
  terraform-version:
    description: 'The version of Terraform to use'
    required: false
    default: 'latest'
  workspace:
    description: 'The Terraform workspace to use'
    required: false
    default: 'default'

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Terraform Init
      run: terraform init -var-file=ci.tfvars
      working-directory: ${{ inputs.dir }}
      shell: bash

    - name: Terraform Workspace Select
      run: terraform workspace select ${{ inputs.workspace }}
      working-directory: ${{ inputs.dir }}
      shell: bash

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{ inputs.dir }}
      shell: bash

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=ci.tfvars
      working-directory: ${{ inputs.dir }}
      shell: bash

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file=ci.tfvars
      working-directory: ${{ inputs.dir }}
      shell: bash
