name: 'Terraform Deploy'
description: 'Deploy infrastructure using Terraform'
inputs:
  working-dir:
    description: 'The directory where the terraform files are located'
    required: true
  terraform-version:
    description: 'The version of Terraform to use'
    required: false
    default: 'latest'
  brunch:
    description: 'The branch name'
    required: false
    default: 'default'
  vars:
    description: 'The Terraform variables file'
    required: false
    default: 'ci.tfvars'

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Install Python dependencies
      run: pip install -r requirements.txt
      working-directory: scripts
      shell: bash

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.working-dir }}
      shell: bash

    - name: Select Workspace
      run: python3 scripts/workspace-change.py ${{ inputs.branch }}
      shell: bash

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{ inputs.working-dir }}
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ inputs.working-dir }}
      shell: bash

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=${{ inputs.vars }}
      working-directory: ${{ inputs.working-dir }}
      shell: bash

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file=${{ inputs.vars }}
      working-directory: ${{ inputs.working-dir }}
      shell: bash
