name: 'SvelteKit Build and Test'
description: 'Build and test SvelteKit code'
inputs:
  node-version:
    description: 'The version of Node to use'
    required: true
  pnpm-version:
    description: 'The version of pnpm to use'
    required: true
  working-dir:
    description: 'The source directory'
    required: false

runs:
  using: "composite"
  steps:
      - name: Setup Node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm ${{ inputs.pnpm-version }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: Install dependencies
        run: pnpm install
        shell: bash
        working-directory: ${{ inputs.working-dir }}

      - name: Build SvelteKit app
        run: pnpm build
        shell: bash
        working-directory: ${{ inputs.working-dir }}

      - name: Test SvelteKit app
        run: pnpm test
        shell: bash
        working-directory: ${{ inputs.working-dir }}
