name: 'Go Build and Test'
description: 'Build and test Go code'
inputs:
  go-version:
    description: 'The version of Go to use'
    required: true
  src:
    description: 'The source directory'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

    - name: Build
      run: go build -v ${{ inputs.src }}
      shell: bash

    - name: Test
      run: go test -v ${{ inputs.src }}
      shell: bash