#!/bin/sh

terraform validate
if "$?"; then
  echo "Some terraform files are not valid. $?"
  exit 1
fi

terraform fmt -recursive -check
if "$?"; then
  echo "Some terraform files are not formatted. Run 'terraform fmt' to fix the formatting. $?"
  exit 1
fi