// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file pb/stredono.proto (package stredono, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum stredono.Currency
 */
export enum Currency {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: PLN = 1;
   */
  PLN = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(Currency)
proto3.util.setEnumType(Currency, "stredono.Currency", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "PLN" },
]);

/**
 * @generated from enum stredono.TipStatus
 */
export enum TipStatus {
  /**
   * @generated from enum value: INITIATED = 0;
   */
  INITIATED = 0,

  /**
   * @generated from enum value: PAYMENT_PENDING = 1;
   */
  PAYMENT_PENDING = 1,

  /**
   * @generated from enum value: PAYMENT_SUCCESS = 2;
   */
  PAYMENT_SUCCESS = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(TipStatus)
proto3.util.setEnumType(TipStatus, "stredono.TipStatus", [
  { no: 0, name: "INITIATED" },
  { no: 1, name: "PAYMENT_PENDING" },
  { no: 2, name: "PAYMENT_SUCCESS" },
]);

/**
 * @generated from enum stredono.AuthLevel
 */
export enum AuthLevel {
  /**
   * @generated from enum value: NONE = 0;
   */
  NONE = 0,

  /**
   * @generated from enum value: EMAIL = 1;
   */
  EMAIL = 1,

  /**
   * @generated from enum value: OIDC = 2;
   */
  OIDC = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(AuthLevel)
proto3.util.setEnumType(AuthLevel, "stredono.AuthLevel", [
  { no: 0, name: "NONE" },
  { no: 1, name: "EMAIL" },
  { no: 2, name: "OIDC" },
]);

/**
 * @generated from enum stredono.EventType
 */
export enum EventType {
  /**
   * @generated from enum value: TIP = 0;
   */
  TIP = 0,

  /**
   * @generated from enum value: CHEER = 1;
   */
  CHEER = 1,

  /**
   * @generated from enum value: FOLLOW = 2;
   */
  FOLLOW = 2,

  /**
   * @generated from enum value: SUBSCRIBE = 3;
   */
  SUBSCRIBE = 3,

  /**
   * @generated from enum value: SUBGIFT = 4;
   */
  SUBGIFT = 4,

  /**
   * @generated from enum value: RAID = 5;
   */
  RAID = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(EventType)
proto3.util.setEnumType(EventType, "stredono.EventType", [
  { no: 0, name: "TIP" },
  { no: 1, name: "CHEER" },
  { no: 2, name: "FOLLOW" },
  { no: 3, name: "SUBSCRIBE" },
  { no: 4, name: "SUBGIFT" },
  { no: 5, name: "RAID" },
]);

/**
 * @generated from enum stredono.AnimationType
 */
export enum AnimationType {
  /**
   * @generated from enum value: PULSE = 0;
   */
  PULSE = 0,

  /**
   * @generated from enum value: HEART_BEAT = 2;
   */
  HEART_BEAT = 2,

  /**
   * @generated from enum value: SHAKE_VERTICALLY = 4;
   */
  SHAKE_VERTICALLY = 4,

  /**
   * @generated from enum value: SHAKE_HORIZONTALLY = 5;
   */
  SHAKE_HORIZONTALLY = 5,

  /**
   * @generated from enum value: TADA = 8;
   */
  TADA = 8,

  /**
   * @generated from enum value: JELLO = 9;
   */
  JELLO = 9,

  /**
   * @generated from enum value: BOUNCE = 10;
   */
  BOUNCE = 10,
}
// Retrieve enum metadata with: proto3.getEnumType(AnimationType)
proto3.util.setEnumType(AnimationType, "stredono.AnimationType", [
  { no: 0, name: "PULSE" },
  { no: 2, name: "HEART_BEAT" },
  { no: 4, name: "SHAKE_VERTICALLY" },
  { no: 5, name: "SHAKE_HORIZONTALLY" },
  { no: 8, name: "TADA" },
  { no: 9, name: "JELLO" },
  { no: 10, name: "BOUNCE" },
]);

/**
 * @generated from enum stredono.Alignment
 */
export enum Alignment {
  /**
   * @generated from enum value: START = 0;
   */
  START = 0,

  /**
   * @generated from enum value: CENTER = 1;
   */
  CENTER = 1,

  /**
   * @generated from enum value: END = 2;
   */
  END = 2,

  /**
   * @generated from enum value: JUSTIFY = 3;
   */
  JUSTIFY = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(Alignment)
proto3.util.setEnumType(Alignment, "stredono.Alignment", [
  { no: 0, name: "START" },
  { no: 1, name: "CENTER" },
  { no: 2, name: "END" },
  { no: 3, name: "JUSTIFY" },
]);

/**
 * @generated from enum stredono.Position
 */
export enum Position {
  /**
   * @generated from enum value: TOP = 0;
   */
  TOP = 0,

  /**
   * @generated from enum value: LEFT = 1;
   */
  LEFT = 1,

  /**
   * @generated from enum value: RIGHT = 2;
   */
  RIGHT = 2,

  /**
   * @generated from enum value: BOTTOM = 3;
   */
  BOTTOM = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(Position)
proto3.util.setEnumType(Position, "stredono.Position", [
  { no: 0, name: "TOP" },
  { no: 1, name: "LEFT" },
  { no: 2, name: "RIGHT" },
  { no: 3, name: "BOTTOM" },
]);

/**
 * @generated from enum stredono.Speed
 */
export enum Speed {
  /**
   * @generated from enum value: OFF = 0;
   */
  OFF = 0,

  /**
   * @generated from enum value: SLOW = 1;
   */
  SLOW = 1,

  /**
   * @generated from enum value: MEDIUM = 2;
   */
  MEDIUM = 2,

  /**
   * @generated from enum value: FAST = 3;
   */
  FAST = 3,

  /**
   * @generated from enum value: FASTER = 4;
   */
  FASTER = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(Speed)
proto3.util.setEnumType(Speed, "stredono.Speed", [
  { no: 0, name: "OFF" },
  { no: 1, name: "SLOW" },
  { no: 2, name: "MEDIUM" },
  { no: 3, name: "FAST" },
  { no: 4, name: "FASTER" },
]);

/**
 * @generated from message stredono.Tip
 */
export class Tip extends Message<Tip> {
  /**
   * @generated from field: string SenderId = 1;
   */
  SenderId = "";

  /**
   * @generated from field: string DisplayName = 2;
   */
  DisplayName = "";

  /**
   * @generated from field: string Email = 3;
   */
  Email = "";

  /**
   * @generated from field: string Message = 4;
   */
  Message = "";

  /**
   * @generated from field: double Amount = 5;
   */
  Amount = 0;

  /**
   * @generated from field: stredono.Currency Currency = 6;
   */
  Currency = Currency.UNKNOWN;

  /**
   * @generated from field: string RecipientId = 7;
   */
  RecipientId = "";

  /**
   * @generated from field: stredono.TipStatus Status = 8;
   */
  Status = TipStatus.INITIATED;

  /**
   * @generated from field: int64 Timestamp = 9;
   */
  Timestamp = protoInt64.zero;

  constructor(data?: PartialMessage<Tip>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.Tip";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "SenderId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "DisplayName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Amount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "Currency", kind: "enum", T: proto3.getEnumType(Currency) },
    { no: 7, name: "RecipientId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "Status", kind: "enum", T: proto3.getEnumType(TipStatus) },
    { no: 9, name: "Timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tip {
    return new Tip().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tip {
    return new Tip().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tip {
    return new Tip().fromJsonString(jsonString, options);
  }

  static equals(a: Tip | PlainMessage<Tip> | undefined, b: Tip | PlainMessage<Tip> | undefined): boolean {
    return proto3.util.equals(Tip, a, b);
  }
}

/**
 * @generated from message stredono.User
 */
export class User extends Message<User> {
  /**
   * @generated from field: string Uid = 1;
   */
  Uid = "";

  /**
   * @generated from field: string Username = 2;
   */
  Username = "";

  /**
   * @generated from field: string DisplayName = 3;
   */
  DisplayName = "";

  /**
   * @generated from field: string Description = 4;
   */
  Description = "";

  /**
   * @generated from field: string PictureUrl = 5;
   */
  PictureUrl = "";

  /**
   * @generated from field: string Url = 6;
   */
  Url = "";

  /**
   * @generated from field: stredono.AuthLevel MinAuthLevel = 7;
   */
  MinAuthLevel = AuthLevel.NONE;

  /**
   * @generated from field: double MinAmount = 8;
   */
  MinAmount = 0;

  /**
   * @generated from field: stredono.Currency Currency = 9;
   */
  Currency = Currency.UNKNOWN;

  constructor(data?: PartialMessage<User>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.User";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Uid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "DisplayName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "PictureUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "Url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "MinAuthLevel", kind: "enum", T: proto3.getEnumType(AuthLevel) },
    { no: 8, name: "MinAmount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 9, name: "Currency", kind: "enum", T: proto3.getEnumType(Currency) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User {
    return new User().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User {
    return new User().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User {
    return new User().fromJsonString(jsonString, options);
  }

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean {
    return proto3.util.equals(User, a, b);
  }
}

/**
 * @generated from message stredono.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from field: string Id = 1;
   */
  Id = "";

  /**
   * @generated from field: stredono.EventType Type = 2;
   */
  Type = EventType.TIP;

  /**
   * @generated from field: map<string, string> Data = 3;
   */
  Data: { [key: string]: string } = {};

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Type", kind: "enum", T: proto3.getEnumType(EventType) },
    { no: 3, name: "Data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

/**
 * @generated from message stredono.UsersAlerts
 */
export class UsersAlerts extends Message<UsersAlerts> {
  /**
   * @generated from field: repeated stredono.Alert Alerts = 1;
   */
  Alerts: Alert[] = [];

  constructor(data?: PartialMessage<UsersAlerts>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.UsersAlerts";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Alerts", kind: "message", T: Alert, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsersAlerts {
    return new UsersAlerts().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsersAlerts {
    return new UsersAlerts().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsersAlerts {
    return new UsersAlerts().fromJsonString(jsonString, options);
  }

  static equals(a: UsersAlerts | PlainMessage<UsersAlerts> | undefined, b: UsersAlerts | PlainMessage<UsersAlerts> | undefined): boolean {
    return proto3.util.equals(UsersAlerts, a, b);
  }
}

/**
 * @generated from message stredono.Alert
 */
export class Alert extends Message<Alert> {
  /**
   * @generated from field: string Id = 1;
   */
  Id = "";

  /**
   * @generated from field: stredono.EventType EventType = 2;
   */
  EventType = EventType.TIP;

  /**
   * @generated from field: string Message = 3;
   */
  Message = "";

  /**
   * @generated from field: double Min = 4;
   */
  Min = 0;

  /**
   * @generated from field: double Max = 5;
   */
  Max = 0;

  /**
   * @generated from field: string GifUrl = 6;
   */
  GifUrl = "";

  /**
   * @generated from field: string SoundUrl = 7;
   */
  SoundUrl = "";

  /**
   * @generated from field: stredono.AnimationType Animation = 8;
   */
  Animation = AnimationType.PULSE;

  /**
   * @generated from field: stredono.Speed AnimationSpeed = 9;
   */
  AnimationSpeed = Speed.OFF;

  /**
   * @generated from field: string TextColor = 10;
   */
  TextColor = "";

  /**
   * @generated from field: string AccentColor = 11;
   */
  AccentColor = "";

  /**
   * @generated from field: stredono.Alignment Alignment = 12;
   */
  Alignment = Alignment.START;

  /**
   * @generated from field: stredono.Position TextPosition = 13;
   */
  TextPosition = Position.TOP;

  constructor(data?: PartialMessage<Alert>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.Alert";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "EventType", kind: "enum", T: proto3.getEnumType(EventType) },
    { no: 3, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Min", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "Max", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "GifUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "SoundUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "Animation", kind: "enum", T: proto3.getEnumType(AnimationType) },
    { no: 9, name: "AnimationSpeed", kind: "enum", T: proto3.getEnumType(Speed) },
    { no: 10, name: "TextColor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "AccentColor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "Alignment", kind: "enum", T: proto3.getEnumType(Alignment) },
    { no: 13, name: "TextPosition", kind: "enum", T: proto3.getEnumType(Position) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Alert {
    return new Alert().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Alert {
    return new Alert().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Alert {
    return new Alert().fromJsonString(jsonString, options);
  }

  static equals(a: Alert | PlainMessage<Alert> | undefined, b: Alert | PlainMessage<Alert> | undefined): boolean {
    return proto3.util.equals(Alert, a, b);
  }
}

/**
 * @generated from message stredono.Token
 */
export class Token extends Message<Token> {
  /**
   * @generated from field: string Access = 1;
   */
  Access = "";

  /**
   * @generated from field: string Refresh = 2;
   */
  Refresh = "";

  constructor(data?: PartialMessage<Token>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.Token";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Access", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Refresh", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Token {
    return new Token().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Token {
    return new Token().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Token {
    return new Token().fromJsonString(jsonString, options);
  }

  static equals(a: Token | PlainMessage<Token> | undefined, b: Token | PlainMessage<Token> | undefined): boolean {
    return proto3.util.equals(Token, a, b);
  }
}

/**
 * @generated from message stredono.TwitchReward
 */
export class TwitchReward extends Message<TwitchReward> {
  /**
   * @generated from field: string Id = 1;
   */
  Id = "";

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * @generated from field: int64 Cost = 3;
   */
  Cost = protoInt64.zero;

  /**
   * @generated from field: bool IsEnabled = 4;
   */
  IsEnabled = false;

  constructor(data?: PartialMessage<TwitchReward>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.TwitchReward";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Cost", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "IsEnabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TwitchReward {
    return new TwitchReward().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TwitchReward {
    return new TwitchReward().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TwitchReward {
    return new TwitchReward().fromJsonString(jsonString, options);
  }

  static equals(a: TwitchReward | PlainMessage<TwitchReward> | undefined, b: TwitchReward | PlainMessage<TwitchReward> | undefined): boolean {
    return proto3.util.equals(TwitchReward, a, b);
  }
}

/**
 * @generated from message stredono.TwitchUser
 */
export class TwitchUser extends Message<TwitchUser> {
  /**
   * @generated from field: string Id = 1;
   */
  Id = "";

  /**
   * @generated from field: string DisplayName = 2;
   */
  DisplayName = "";

  /**
   * @generated from field: string Login = 3;
   */
  Login = "";

  /**
   * @generated from field: string AvatarUrl = 4;
   */
  AvatarUrl = "";

  /**
   * @generated from field: string Description = 5;
   */
  Description = "";

  /**
   * @generated from field: int64 CreationTimestamp = 6;
   */
  CreationTimestamp = protoInt64.zero;

  constructor(data?: PartialMessage<TwitchUser>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.TwitchUser";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "DisplayName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Login", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "AvatarUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "CreationTimestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TwitchUser {
    return new TwitchUser().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TwitchUser {
    return new TwitchUser().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TwitchUser {
    return new TwitchUser().fromJsonString(jsonString, options);
  }

  static equals(a: TwitchUser | PlainMessage<TwitchUser> | undefined, b: TwitchUser | PlainMessage<TwitchUser> | undefined): boolean {
    return proto3.util.equals(TwitchUser, a, b);
  }
}

