// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file pb/user.proto (package stredono, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum stredono.Currency
 */
export enum Currency {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: BITS = 1;
   */
  BITS = 1,

  /**
   * @generated from enum value: PLN = 2;
   */
  PLN = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Currency)
proto3.util.setEnumType(Currency, "stredono.Currency", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "BITS" },
  { no: 2, name: "PLN" },
]);

/**
 * @generated from enum stredono.AlertType
 */
export enum AlertType {
  /**
   * @generated from enum value: DONATE = 0;
   */
  DONATE = 0,

  /**
   * @generated from enum value: FOLLOW = 1;
   */
  FOLLOW = 1,

  /**
   * @generated from enum value: SUBSCRIBE = 2;
   */
  SUBSCRIBE = 2,

  /**
   * @generated from enum value: SUBGIFT = 3;
   */
  SUBGIFT = 3,

  /**
   * @generated from enum value: RAID = 4;
   */
  RAID = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(AlertType)
proto3.util.setEnumType(AlertType, "stredono.AlertType", [
  { no: 0, name: "DONATE" },
  { no: 1, name: "FOLLOW" },
  { no: 2, name: "SUBSCRIBE" },
  { no: 3, name: "SUBGIFT" },
  { no: 4, name: "RAID" },
]);

/**
 * @generated from enum stredono.TextToSpeechService
 */
export enum TextToSpeechService {
  /**
   * @generated from enum value: GOOGLE = 0;
   */
  GOOGLE = 0,

  /**
   * @generated from enum value: ELEVENLABS = 1;
   */
  ELEVENLABS = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(TextToSpeechService)
proto3.util.setEnumType(TextToSpeechService, "stredono.TextToSpeechService", [
  { no: 0, name: "GOOGLE" },
  { no: 1, name: "ELEVENLABS" },
]);

/**
 * @generated from enum stredono.AnimationType
 */
export enum AnimationType {
  /**
   * @generated from enum value: SHAKE = 0;
   */
  SHAKE = 0,

  /**
   * @generated from enum value: BOUNCE = 1;
   */
  BOUNCE = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(AnimationType)
proto3.util.setEnumType(AnimationType, "stredono.AnimationType", [
  { no: 0, name: "SHAKE" },
  { no: 1, name: "BOUNCE" },
]);

/**
 * @generated from message stredono.User
 */
export class User extends Message<User> {
  /**
   * @generated from field: string Username = 1;
   */
  Username = "";

  /**
   * @generated from field: string DisplayName = 2;
   */
  DisplayName = "";

  /**
   * @generated from field: string Uid = 3;
   */
  Uid = "";

  /**
   * @generated from field: string Url = 4;
   */
  Url = "";

  /**
   * @generated from field: string Description = 5;
   */
  Description = "";

  /**
   * @generated from field: string AvatarUrl = 6;
   */
  AvatarUrl = "";

  /**
   * @generated from field: double MinimumAmount = 7;
   */
  MinimumAmount = 0;

  /**
   * @generated from field: stredono.Currency Currency = 8;
   */
  Currency = Currency.UNKNOWN;

  /**
   * @generated from field: repeated stredono.Alert Alerts = 9;
   */
  Alerts: Alert[] = [];

  constructor(data?: PartialMessage<User>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.User";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "DisplayName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Uid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "AvatarUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "MinimumAmount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "Currency", kind: "enum", T: proto3.getEnumType(Currency) },
    { no: 9, name: "Alerts", kind: "message", T: Alert, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User {
    return new User().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User {
    return new User().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User {
    return new User().fromJsonString(jsonString, options);
  }

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean {
    return proto3.util.equals(User, a, b);
  }
}

/**
 * @generated from message stredono.TextToSpeechSettings
 */
export class TextToSpeechSettings extends Message<TextToSpeechSettings> {
  /**
   * @generated from field: stredono.TextToSpeechService Service = 1;
   */
  Service = TextToSpeechService.GOOGLE;

  /**
   * @generated from field: string Voice = 2;
   */
  Voice = "";

  /**
   * @generated from field: string Language = 3;
   */
  Language = "";

  constructor(data?: PartialMessage<TextToSpeechSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.TextToSpeechSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Service", kind: "enum", T: proto3.getEnumType(TextToSpeechService) },
    { no: 2, name: "Voice", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Language", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TextToSpeechSettings {
    return new TextToSpeechSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TextToSpeechSettings {
    return new TextToSpeechSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TextToSpeechSettings {
    return new TextToSpeechSettings().fromJsonString(jsonString, options);
  }

  static equals(a: TextToSpeechSettings | PlainMessage<TextToSpeechSettings> | undefined, b: TextToSpeechSettings | PlainMessage<TextToSpeechSettings> | undefined): boolean {
    return proto3.util.equals(TextToSpeechSettings, a, b);
  }
}

/**
 * @generated from message stredono.AmountTrigger
 */
export class AmountTrigger extends Message<AmountTrigger> {
  /**
   * @generated from field: double Min = 1;
   */
  Min = 0;

  /**
   * @generated from field: double Max = 2;
   */
  Max = 0;

  constructor(data?: PartialMessage<AmountTrigger>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.AmountTrigger";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Min", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "Max", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AmountTrigger {
    return new AmountTrigger().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AmountTrigger {
    return new AmountTrigger().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AmountTrigger {
    return new AmountTrigger().fromJsonString(jsonString, options);
  }

  static equals(a: AmountTrigger | PlainMessage<AmountTrigger> | undefined, b: AmountTrigger | PlainMessage<AmountTrigger> | undefined): boolean {
    return proto3.util.equals(AmountTrigger, a, b);
  }
}

/**
 * @generated from message stredono.Alert
 */
export class Alert extends Message<Alert> {
  /**
   * @generated from field: string Id = 1;
   */
  Id = "";

  /**
   * @generated from field: stredono.AlertType Type = 2;
   */
  Type = AlertType.DONATE;

  /**
   * @generated from field: optional stredono.AmountTrigger AmountTrigger = 3;
   */
  AmountTrigger?: AmountTrigger;

  /**
   * @generated from field: string Template = 4;
   */
  Template = "";

  /**
   * @generated from field: stredono.AlertStyle Style = 5;
   */
  Style?: AlertStyle;

  /**
   * @generated from field: optional stredono.TextToSpeechSettings TtsSettings = 6;
   */
  TtsSettings?: TextToSpeechSettings;

  constructor(data?: PartialMessage<Alert>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.Alert";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Type", kind: "enum", T: proto3.getEnumType(AlertType) },
    { no: 3, name: "AmountTrigger", kind: "message", T: AmountTrigger, opt: true },
    { no: 4, name: "Template", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Style", kind: "message", T: AlertStyle },
    { no: 6, name: "TtsSettings", kind: "message", T: TextToSpeechSettings, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Alert {
    return new Alert().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Alert {
    return new Alert().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Alert {
    return new Alert().fromJsonString(jsonString, options);
  }

  static equals(a: Alert | PlainMessage<Alert> | undefined, b: Alert | PlainMessage<Alert> | undefined): boolean {
    return proto3.util.equals(Alert, a, b);
  }
}

/**
 * @generated from message stredono.AlertStyle
 */
export class AlertStyle extends Message<AlertStyle> {
  /**
   * @generated from field: string GifUrl = 1;
   */
  GifUrl = "";

  /**
   * @generated from field: string SoundUrl = 2;
   */
  SoundUrl = "";

  /**
   * @generated from field: stredono.AnimationType Animation = 3;
   */
  Animation = AnimationType.SHAKE;

  /**
   * @generated from field: string TextColor = 4;
   */
  TextColor = "";

  /**
   * @generated from field: string AccentColor = 5;
   */
  AccentColor = "";

  constructor(data?: PartialMessage<AlertStyle>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.AlertStyle";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "GifUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "SoundUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Animation", kind: "enum", T: proto3.getEnumType(AnimationType) },
    { no: 4, name: "TextColor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "AccentColor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AlertStyle {
    return new AlertStyle().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AlertStyle {
    return new AlertStyle().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AlertStyle {
    return new AlertStyle().fromJsonString(jsonString, options);
  }

  static equals(a: AlertStyle | PlainMessage<AlertStyle> | undefined, b: AlertStyle | PlainMessage<AlertStyle> | undefined): boolean {
    return proto3.util.equals(AlertStyle, a, b);
  }
}

/**
 * @generated from message stredono.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from field: repeated string Users = 1;
   */
  Users: string[] = [];

  /**
   * @generated from field: repeated double Amounts = 2;
   */
  Amounts: number[] = [];

  /**
   * @generated from field: optional string Currency = 3;
   */
  Currency?: string;

  /**
   * @generated from field: optional string Message = 4;
   */
  Message?: string;

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Users", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "Amounts", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, repeated: true },
    { no: 3, name: "Currency", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

/**
 * @generated from message stredono.Token
 */
export class Token extends Message<Token> {
  /**
   * @generated from field: string Access = 1;
   */
  Access = "";

  /**
   * @generated from field: string Refresh = 2;
   */
  Refresh = "";

  constructor(data?: PartialMessage<Token>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.Token";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Access", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Refresh", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Token {
    return new Token().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Token {
    return new Token().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Token {
    return new Token().fromJsonString(jsonString, options);
  }

  static equals(a: Token | PlainMessage<Token> | undefined, b: Token | PlainMessage<Token> | undefined): boolean {
    return proto3.util.equals(Token, a, b);
  }
}

