// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file pb/user_data.proto (package stredono, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { MediaRequest } from "./media_request_pb.js";
import { EventsSettings } from "./events_settings_pb.js";
import { TTSSettings } from "./tts_settings_pb.js";
import { Alert } from "./alert_pb.js";

/**
 * @generated from message stredono.UserData
 */
export class UserData extends Message<UserData> {
  /**
   * @generated from field: stredono.UserSettings Settings = 1;
   */
  Settings?: UserSettings;

  /**
   * @generated from field: stredono.MediaRequest Media = 2;
   */
  Media?: MediaRequest;

  /**
   * @generated from field: map<string, string> Commands = 3;
   */
  Commands: { [key: string]: string } = {};

  constructor(data?: PartialMessage<UserData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.UserData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Settings", kind: "message", T: UserSettings },
    { no: 2, name: "Media", kind: "message", T: MediaRequest },
    { no: 3, name: "Commands", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserData {
    return new UserData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserData {
    return new UserData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserData {
    return new UserData().fromJsonString(jsonString, options);
  }

  static equals(a: UserData | PlainMessage<UserData> | undefined, b: UserData | PlainMessage<UserData> | undefined): boolean {
    return proto3.util.equals(UserData, a, b);
  }
}

/**
 * @generated from message stredono.UserSettings
 */
export class UserSettings extends Message<UserSettings> {
  /**
   * @generated from field: stredono.EventsSettings Events = 1;
   */
  Events?: EventsSettings;

  /**
   * @generated from field: stredono.TTSSettings TTS = 2;
   */
  TTS?: TTSSettings;

  /**
   * @generated from field: repeated stredono.Alert Alerts = 3;
   */
  Alerts: Alert[] = [];

  /**
   * @generated from field: stredono.OverlaySettings Overlay = 4;
   */
  Overlay?: OverlaySettings;

  constructor(data?: PartialMessage<UserSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.UserSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Events", kind: "message", T: EventsSettings },
    { no: 2, name: "TTS", kind: "message", T: TTSSettings },
    { no: 3, name: "Alerts", kind: "message", T: Alert, repeated: true },
    { no: 4, name: "Overlay", kind: "message", T: OverlaySettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserSettings {
    return new UserSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserSettings {
    return new UserSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserSettings {
    return new UserSettings().fromJsonString(jsonString, options);
  }

  static equals(a: UserSettings | PlainMessage<UserSettings> | undefined, b: UserSettings | PlainMessage<UserSettings> | undefined): boolean {
    return proto3.util.equals(UserSettings, a, b);
  }
}

/**
 * @generated from message stredono.OverlaySettings
 */
export class OverlaySettings extends Message<OverlaySettings> {
  /**
   * @generated from field: string Key = 1;
   */
  Key = "";

  constructor(data?: PartialMessage<OverlaySettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.OverlaySettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OverlaySettings {
    return new OverlaySettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OverlaySettings {
    return new OverlaySettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OverlaySettings {
    return new OverlaySettings().fromJsonString(jsonString, options);
  }

  static equals(a: OverlaySettings | PlainMessage<OverlaySettings> | undefined, b: OverlaySettings | PlainMessage<OverlaySettings> | undefined): boolean {
    return proto3.util.equals(OverlaySettings, a, b);
  }
}

