// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTransactionNode is an autogenerated mock type for the TransactionNode type
type MockTransactionNode struct {
	mock.Mock
}

type MockTransactionNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionNode) EXPECT() *MockTransactionNode_Expecter {
	return &MockTransactionNode_Expecter{mock: &_m.Mock}
}

// Unmarshal provides a mock function with given fields: v
func (_m *MockTransactionNode) Unmarshal(v interface{}) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionNode_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockTransactionNode_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - v interface{}
func (_e *MockTransactionNode_Expecter) Unmarshal(v interface{}) *MockTransactionNode_Unmarshal_Call {
	return &MockTransactionNode_Unmarshal_Call{Call: _e.mock.On("Unmarshal", v)}
}

func (_c *MockTransactionNode_Unmarshal_Call) Run(run func(v interface{})) *MockTransactionNode_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockTransactionNode_Unmarshal_Call) Return(_a0 error) *MockTransactionNode_Unmarshal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionNode_Unmarshal_Call) RunAndReturn(run func(interface{}) error) *MockTransactionNode_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionNode creates a new instance of MockTransactionNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionNode {
	mock := &MockTransactionNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
