// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	modules "github.com/pkulik0/stredono/cloud/platform/modules"
	mock "github.com/stretchr/testify/mock"
)

// MockNoSqlDb is an autogenerated mock type for the NoSqlDb type
type MockNoSqlDb struct {
	mock.Mock
}

type MockNoSqlDb_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoSqlDb) EXPECT() *MockNoSqlDb_Expecter {
	return &MockNoSqlDb_Expecter{mock: &_m.Mock}
}

// Collection provides a mock function with given fields: path
func (_m *MockNoSqlDb) Collection(path string) modules.Collection {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Collection")
	}

	var r0 modules.Collection
	if rf, ok := ret.Get(0).(func(string) modules.Collection); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(modules.Collection)
		}
	}

	return r0
}

// MockNoSqlDb_Collection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collection'
type MockNoSqlDb_Collection_Call struct {
	*mock.Call
}

// Collection is a helper method to define mock.On call
//   - path string
func (_e *MockNoSqlDb_Expecter) Collection(path interface{}) *MockNoSqlDb_Collection_Call {
	return &MockNoSqlDb_Collection_Call{Call: _e.mock.On("Collection", path)}
}

func (_c *MockNoSqlDb_Collection_Call) Run(run func(path string)) *MockNoSqlDb_Collection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNoSqlDb_Collection_Call) Return(_a0 modules.Collection) *MockNoSqlDb_Collection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoSqlDb_Collection_Call) RunAndReturn(run func(string) modules.Collection) *MockNoSqlDb_Collection_Call {
	_c.Call.Return(run)
	return _c
}

// RunTransaction provides a mock function with given fields: ctx, f
func (_m *MockNoSqlDb) RunTransaction(ctx context.Context, f func(context.Context, modules.Transaction) error) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for RunTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, modules.Transaction) error) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNoSqlDb_RunTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTransaction'
type MockNoSqlDb_RunTransaction_Call struct {
	*mock.Call
}

// RunTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(context.Context , modules.Transaction) error
func (_e *MockNoSqlDb_Expecter) RunTransaction(ctx interface{}, f interface{}) *MockNoSqlDb_RunTransaction_Call {
	return &MockNoSqlDb_RunTransaction_Call{Call: _e.mock.On("RunTransaction", ctx, f)}
}

func (_c *MockNoSqlDb_RunTransaction_Call) Run(run func(ctx context.Context, f func(context.Context, modules.Transaction) error)) *MockNoSqlDb_RunTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, modules.Transaction) error))
	})
	return _c
}

func (_c *MockNoSqlDb_RunTransaction_Call) Return(_a0 error) *MockNoSqlDb_RunTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoSqlDb_RunTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context, modules.Transaction) error) error) *MockNoSqlDb_RunTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNoSqlDb creates a new instance of MockNoSqlDb. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoSqlDb(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoSqlDb {
	mock := &MockNoSqlDb{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
