// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockToken is an autogenerated mock type for the Token type
type MockToken struct {
	mock.Mock
}

type MockToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToken) EXPECT() *MockToken_Expecter {
	return &MockToken_Expecter{mock: &_m.Mock}
}

// UserId provides a mock function with given fields:
func (_m *MockToken) UserId() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserId")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockToken_UserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserId'
type MockToken_UserId_Call struct {
	*mock.Call
}

// UserId is a helper method to define mock.On call
func (_e *MockToken_Expecter) UserId() *MockToken_UserId_Call {
	return &MockToken_UserId_Call{Call: _e.mock.On("UserId")}
}

func (_c *MockToken_UserId_Call) Run(run func()) *MockToken_UserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_UserId_Call) Return(_a0 string) *MockToken_UserId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToken_UserId_Call) RunAndReturn(run func() string) *MockToken_UserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockToken creates a new instance of MockToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToken {
	mock := &MockToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
