// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: pb/alerts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertsKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AlertsKey) Reset() {
	*x = AlertsKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_alerts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertsKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertsKey) ProtoMessage() {}

func (x *AlertsKey) ProtoReflect() protoreflect.Message {
	mi := &file_pb_alerts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertsKey.ProtoReflect.Descriptor instead.
func (*AlertsKey) Descriptor() ([]byte, []int) {
	return file_pb_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *AlertsKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From     float32 `protobuf:"fixed32,2,opt,name=from,proto3" json:"from,omitempty"`
	To       float32 `protobuf:"fixed32,3,opt,name=to,proto3" json:"to,omitempty"`
	Template string  `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	GifUrl   string  `protobuf:"bytes,5,opt,name=gifUrl,proto3" json:"gifUrl,omitempty"`
	SoundUrl string  `protobuf:"bytes,6,opt,name=soundUrl,proto3" json:"soundUrl,omitempty"`
}

func (x *Alert) Reset() {
	*x = Alert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_alerts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_pb_alerts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_pb_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetFrom() float32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Alert) GetTo() float32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Alert) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Alert) GetGifUrl() string {
	if x != nil {
		return x.GifUrl
	}
	return ""
}

func (x *Alert) GetSoundUrl() string {
	if x != nil {
		return x.SoundUrl
	}
	return ""
}

var File_pb_alerts_proto protoreflect.FileDescriptor

var file_pb_alerts_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x22, 0x1d, 0x0a, 0x09, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x05, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x69, 0x66, 0x55, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x69, 0x66, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x72, 0x6c, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x75, 0x6c, 0x69, 0x6b, 0x30, 0x2f, 0x73,
	0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_alerts_proto_rawDescOnce sync.Once
	file_pb_alerts_proto_rawDescData = file_pb_alerts_proto_rawDesc
)

func file_pb_alerts_proto_rawDescGZIP() []byte {
	file_pb_alerts_proto_rawDescOnce.Do(func() {
		file_pb_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_alerts_proto_rawDescData)
	})
	return file_pb_alerts_proto_rawDescData
}

var file_pb_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_alerts_proto_goTypes = []interface{}{
	(*AlertsKey)(nil), // 0: stredono.AlertsKey
	(*Alert)(nil),     // 1: stredono.Alert
}
var file_pb_alerts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_alerts_proto_init() }
func file_pb_alerts_proto_init() {
	if File_pb_alerts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_alerts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertsKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_alerts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_alerts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_alerts_proto_goTypes,
		DependencyIndexes: file_pb_alerts_proto_depIdxs,
		MessageInfos:      file_pb_alerts_proto_msgTypes,
	}.Build()
	File_pb_alerts_proto = out.File
	file_pb_alerts_proto_rawDesc = nil
	file_pb_alerts_proto_goTypes = nil
	file_pb_alerts_proto_depIdxs = nil
}
