// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file pb/functions.proto (package stredono, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum stredono.DonateStatus
 */
export enum DonateStatus {
  /**
   * @generated from enum value: INITIATED = 0;
   */
  INITIATED = 0,

  /**
   * @generated from enum value: PAYMENT_PENDING = 1;
   */
  PAYMENT_PENDING = 1,

  /**
   * @generated from enum value: PAYMENT_SUCCESS = 2;
   */
  PAYMENT_SUCCESS = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(DonateStatus)
proto3.util.setEnumType(DonateStatus, "stredono.DonateStatus", [
  { no: 0, name: "INITIATED" },
  { no: 1, name: "PAYMENT_PENDING" },
  { no: 2, name: "PAYMENT_SUCCESS" },
]);

/**
 * @generated from message stredono.SendDonateRequest
 */
export class SendDonateRequest extends Message<SendDonateRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string sender = 2;
   */
  sender = "";

  /**
   * @generated from field: string email = 3;
   */
  email = "";

  /**
   * @generated from field: string message = 4;
   */
  message = "";

  /**
   * @generated from field: float amount = 5;
   */
  amount = 0;

  /**
   * @generated from field: string currency = 6;
   */
  currency = "";

  /**
   * @generated from field: string recipientId = 7;
   */
  recipientId = "";

  /**
   * @generated from field: stredono.DonateStatus status = 8;
   */
  status = DonateStatus.INITIATED;

  /**
   * @generated from field: google.protobuf.Timestamp created = 9;
   */
  created?: Timestamp;

  constructor(data?: PartialMessage<SendDonateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.SendDonateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "amount", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 6, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "recipientId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "status", kind: "enum", T: proto3.getEnumType(DonateStatus) },
    { no: 9, name: "created", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendDonateRequest {
    return new SendDonateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendDonateRequest {
    return new SendDonateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendDonateRequest {
    return new SendDonateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendDonateRequest | PlainMessage<SendDonateRequest> | undefined, b: SendDonateRequest | PlainMessage<SendDonateRequest> | undefined): boolean {
    return proto3.util.equals(SendDonateRequest, a, b);
  }
}

/**
 * @generated from message stredono.SendDonateResponse
 */
export class SendDonateResponse extends Message<SendDonateResponse> {
  /**
   * @generated from field: string redirectUrl = 1;
   */
  redirectUrl = "";

  constructor(data?: PartialMessage<SendDonateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stredono.SendDonateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "redirectUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendDonateResponse {
    return new SendDonateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendDonateResponse {
    return new SendDonateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendDonateResponse {
    return new SendDonateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendDonateResponse | PlainMessage<SendDonateResponse> | undefined, b: SendDonateResponse | PlainMessage<SendDonateResponse> | undefined): boolean {
    return proto3.util.equals(SendDonateResponse, a, b);
  }
}

