// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: pb/chat_role.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_NORMAL     Role = 0
	Role_SUBSCRIBER Role = 1
	Role_VIP        Role = 2
	Role_MODERATOR  Role = 3
	Role_OWNER      Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "NORMAL",
		1: "SUBSCRIBER",
		2: "VIP",
		3: "MODERATOR",
		4: "OWNER",
	}
	Role_value = map[string]int32{
		"NORMAL":     0,
		"SUBSCRIBER": 1,
		"VIP":        2,
		"MODERATOR":  3,
		"OWNER":      4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_chat_role_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_pb_chat_role_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_pb_chat_role_proto_rawDescGZIP(), []int{0}
}

var File_pb_chat_role_proto protoreflect.FileDescriptor

var file_pb_chat_role_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2a, 0x45,
	0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x52,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x56, 0x49, 0x50, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x4f, 0x44, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x57,
	0x4e, 0x45, 0x52, 0x10, 0x04, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x75, 0x6c, 0x69, 0x6b, 0x30, 0x2f, 0x73, 0x74, 0x72, 0x65,
	0x64, 0x6f, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_chat_role_proto_rawDescOnce sync.Once
	file_pb_chat_role_proto_rawDescData = file_pb_chat_role_proto_rawDesc
)

func file_pb_chat_role_proto_rawDescGZIP() []byte {
	file_pb_chat_role_proto_rawDescOnce.Do(func() {
		file_pb_chat_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_chat_role_proto_rawDescData)
	})
	return file_pb_chat_role_proto_rawDescData
}

var file_pb_chat_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_chat_role_proto_goTypes = []interface{}{
	(Role)(0), // 0: stredono.Role
}
var file_pb_chat_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_chat_role_proto_init() }
func file_pb_chat_role_proto_init() {
	if File_pb_chat_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_chat_role_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_chat_role_proto_goTypes,
		DependencyIndexes: file_pb_chat_role_proto_depIdxs,
		EnumInfos:         file_pb_chat_role_proto_enumTypes,
	}.Build()
	File_pb_chat_role_proto = out.File
	file_pb_chat_role_proto_rawDesc = nil
	file_pb_chat_role_proto_goTypes = nil
	file_pb_chat_role_proto_depIdxs = nil
}
