// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: pb/enums.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_UNKNOWN Currency = 0
	Currency_PLN     Currency = 1
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "UNKNOWN",
		1: "PLN",
	}
	Currency_value = map[string]int32{
		"UNKNOWN": 0,
		"PLN":     1,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enums_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_pb_enums_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_pb_enums_proto_rawDescGZIP(), []int{0}
}

type Frequency int32

const (
	Frequency_NEVER              Frequency = 0
	Frequency_ALWAYS             Frequency = 1
	Frequency_EVERY_MINUTE       Frequency = 2
	Frequency_EVERY_FIVE_MINUTES Frequency = 3
	Frequency_EVERY_QUARTER_HOUR Frequency = 4
	Frequency_EVERY_HALF_HOUR    Frequency = 5
	Frequency_EVERY_HOUR         Frequency = 6
)

// Enum value maps for Frequency.
var (
	Frequency_name = map[int32]string{
		0: "NEVER",
		1: "ALWAYS",
		2: "EVERY_MINUTE",
		3: "EVERY_FIVE_MINUTES",
		4: "EVERY_QUARTER_HOUR",
		5: "EVERY_HALF_HOUR",
		6: "EVERY_HOUR",
	}
	Frequency_value = map[string]int32{
		"NEVER":              0,
		"ALWAYS":             1,
		"EVERY_MINUTE":       2,
		"EVERY_FIVE_MINUTES": 3,
		"EVERY_QUARTER_HOUR": 4,
		"EVERY_HALF_HOUR":    5,
		"EVERY_HOUR":         6,
	}
)

func (x Frequency) Enum() *Frequency {
	p := new(Frequency)
	*p = x
	return p
}

func (x Frequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Frequency) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enums_proto_enumTypes[1].Descriptor()
}

func (Frequency) Type() protoreflect.EnumType {
	return &file_pb_enums_proto_enumTypes[1]
}

func (x Frequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Frequency.Descriptor instead.
func (Frequency) EnumDescriptor() ([]byte, []int) {
	return file_pb_enums_proto_rawDescGZIP(), []int{1}
}

type Tier int32

const (
	Tier_BASIC Tier = 0
	Tier_PLUS  Tier = 1
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "BASIC",
		1: "PLUS",
	}
	Tier_value = map[string]int32{
		"BASIC": 0,
		"PLUS":  1,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enums_proto_enumTypes[2].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_pb_enums_proto_enumTypes[2]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_pb_enums_proto_rawDescGZIP(), []int{2}
}

var File_pb_enums_proto protoreflect.FileDescriptor

var file_pb_enums_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2a, 0x20, 0x0a, 0x08, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4c, 0x4e, 0x10, 0x01, 0x2a, 0x89, 0x01, 0x0a,
	0x09, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x45,
	0x56, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4c, 0x57, 0x41, 0x59, 0x53, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x4d, 0x49, 0x4e, 0x55, 0x54,
	0x45, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x46, 0x49, 0x56,
	0x45, 0x5f, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x53, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x45,
	0x56, 0x45, 0x52, 0x59, 0x5f, 0x51, 0x55, 0x41, 0x52, 0x54, 0x45, 0x52, 0x5f, 0x48, 0x4f, 0x55,
	0x52, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x48, 0x41, 0x4c,
	0x46, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x56, 0x45, 0x52,
	0x59, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x10, 0x06, 0x2a, 0x1b, 0x0a, 0x04, 0x54, 0x69, 0x65, 0x72,
	0x12, 0x09, 0x0a, 0x05, 0x42, 0x41, 0x53, 0x49, 0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x4c, 0x55, 0x53, 0x10, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x75, 0x6c, 0x69, 0x6b, 0x30, 0x2f, 0x73, 0x74, 0x72, 0x65,
	0x64, 0x6f, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_enums_proto_rawDescOnce sync.Once
	file_pb_enums_proto_rawDescData = file_pb_enums_proto_rawDesc
)

func file_pb_enums_proto_rawDescGZIP() []byte {
	file_pb_enums_proto_rawDescOnce.Do(func() {
		file_pb_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_enums_proto_rawDescData)
	})
	return file_pb_enums_proto_rawDescData
}

var file_pb_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_enums_proto_goTypes = []interface{}{
	(Currency)(0),  // 0: stredono.Currency
	(Frequency)(0), // 1: stredono.Frequency
	(Tier)(0),      // 2: stredono.Tier
}
var file_pb_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_enums_proto_init() }
func file_pb_enums_proto_init() {
	if File_pb_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_enums_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_enums_proto_goTypes,
		DependencyIndexes: file_pb_enums_proto_depIdxs,
		EnumInfos:         file_pb_enums_proto_enumTypes,
	}.Build()
	File_pb_enums_proto = out.File
	file_pb_enums_proto_rawDesc = nil
	file_pb_enums_proto_goTypes = nil
	file_pb_enums_proto_depIdxs = nil
}
