// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: pb/stredono.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_UNKNOWN Currency = 0
	Currency_BITS    Currency = 1
	Currency_PLN     Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "UNKNOWN",
		1: "BITS",
		2: "PLN",
	}
	Currency_value = map[string]int32{
		"UNKNOWN": 0,
		"BITS":    1,
		"PLN":     2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_stredono_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_pb_stredono_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{0}
}

type TipStatus int32

const (
	TipStatus_INITIATED       TipStatus = 0
	TipStatus_PAYMENT_PENDING TipStatus = 1
	TipStatus_PAYMENT_SUCCESS TipStatus = 2
)

// Enum value maps for TipStatus.
var (
	TipStatus_name = map[int32]string{
		0: "INITIATED",
		1: "PAYMENT_PENDING",
		2: "PAYMENT_SUCCESS",
	}
	TipStatus_value = map[string]int32{
		"INITIATED":       0,
		"PAYMENT_PENDING": 1,
		"PAYMENT_SUCCESS": 2,
	}
)

func (x TipStatus) Enum() *TipStatus {
	p := new(TipStatus)
	*p = x
	return p
}

func (x TipStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TipStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_stredono_proto_enumTypes[1].Descriptor()
}

func (TipStatus) Type() protoreflect.EnumType {
	return &file_pb_stredono_proto_enumTypes[1]
}

func (x TipStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TipStatus.Descriptor instead.
func (TipStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{1}
}

type AlertType int32

const (
	AlertType_DONATE    AlertType = 0
	AlertType_FOLLOW    AlertType = 1
	AlertType_SUBSCRIBE AlertType = 2
	AlertType_SUBGIFT   AlertType = 3
	AlertType_RAID      AlertType = 4
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "DONATE",
		1: "FOLLOW",
		2: "SUBSCRIBE",
		3: "SUBGIFT",
		4: "RAID",
	}
	AlertType_value = map[string]int32{
		"DONATE":    0,
		"FOLLOW":    1,
		"SUBSCRIBE": 2,
		"SUBGIFT":   3,
		"RAID":      4,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_stredono_proto_enumTypes[2].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_pb_stredono_proto_enumTypes[2]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{2}
}

type TextToSpeechService int32

const (
	TextToSpeechService_GOOGLE     TextToSpeechService = 0
	TextToSpeechService_ELEVENLABS TextToSpeechService = 1
)

// Enum value maps for TextToSpeechService.
var (
	TextToSpeechService_name = map[int32]string{
		0: "GOOGLE",
		1: "ELEVENLABS",
	}
	TextToSpeechService_value = map[string]int32{
		"GOOGLE":     0,
		"ELEVENLABS": 1,
	}
)

func (x TextToSpeechService) Enum() *TextToSpeechService {
	p := new(TextToSpeechService)
	*p = x
	return p
}

func (x TextToSpeechService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextToSpeechService) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_stredono_proto_enumTypes[3].Descriptor()
}

func (TextToSpeechService) Type() protoreflect.EnumType {
	return &file_pb_stredono_proto_enumTypes[3]
}

func (x TextToSpeechService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextToSpeechService.Descriptor instead.
func (TextToSpeechService) EnumDescriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{3}
}

type AnimationType int32

const (
	AnimationType_SHAKE  AnimationType = 0
	AnimationType_BOUNCE AnimationType = 1
)

// Enum value maps for AnimationType.
var (
	AnimationType_name = map[int32]string{
		0: "SHAKE",
		1: "BOUNCE",
	}
	AnimationType_value = map[string]int32{
		"SHAKE":  0,
		"BOUNCE": 1,
	}
)

func (x AnimationType) Enum() *AnimationType {
	p := new(AnimationType)
	*p = x
	return p
}

func (x AnimationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnimationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_stredono_proto_enumTypes[4].Descriptor()
}

func (AnimationType) Type() protoreflect.EnumType {
	return &file_pb_stredono_proto_enumTypes[4]
}

func (x AnimationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnimationType.Descriptor instead.
func (AnimationType) EnumDescriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{4}
}

type Tip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender      string    `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Email       string    `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Message     string    `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Amount      float64   `protobuf:"fixed64,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Currency    Currency  `protobuf:"varint,5,opt,name=Currency,proto3,enum=stredono.Currency" json:"Currency,omitempty"`
	RecipientId string    `protobuf:"bytes,6,opt,name=RecipientId,proto3" json:"RecipientId,omitempty"`
	Status      TipStatus `protobuf:"varint,7,opt,name=Status,proto3,enum=stredono.TipStatus" json:"Status,omitempty"`
	Timestamp   int64     `protobuf:"varint,8,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *Tip) Reset() {
	*x = Tip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tip) ProtoMessage() {}

func (x *Tip) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tip.ProtoReflect.Descriptor instead.
func (*Tip) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{0}
}

func (x *Tip) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Tip) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Tip) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Tip) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Tip) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_UNKNOWN
}

func (x *Tip) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *Tip) GetStatus() TipStatus {
	if x != nil {
		return x.Status
	}
	return TipStatus_INITIATED
}

func (x *Tip) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username      string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	DisplayName   string   `protobuf:"bytes,2,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Uid           string   `protobuf:"bytes,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Url           string   `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	Description   string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	PictureUrl    string   `protobuf:"bytes,6,opt,name=PictureUrl,proto3" json:"PictureUrl,omitempty"`
	MinimumAmount float64  `protobuf:"fixed64,7,opt,name=MinimumAmount,proto3" json:"MinimumAmount,omitempty"`
	Currency      Currency `protobuf:"varint,8,opt,name=Currency,proto3,enum=stredono.Currency" json:"Currency,omitempty"`
	Alerts        []*Alert `protobuf:"bytes,9,rep,name=Alerts,proto3" json:"Alerts,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *User) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetPictureUrl() string {
	if x != nil {
		return x.PictureUrl
	}
	return ""
}

func (x *User) GetMinimumAmount() float64 {
	if x != nil {
		return x.MinimumAmount
	}
	return 0
}

func (x *User) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_UNKNOWN
}

func (x *User) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type TextToSpeechSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service  TextToSpeechService `protobuf:"varint,1,opt,name=Service,proto3,enum=stredono.TextToSpeechService" json:"Service,omitempty"`
	Voice    string              `protobuf:"bytes,2,opt,name=Voice,proto3" json:"Voice,omitempty"`
	Language string              `protobuf:"bytes,3,opt,name=Language,proto3" json:"Language,omitempty"`
}

func (x *TextToSpeechSettings) Reset() {
	*x = TextToSpeechSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextToSpeechSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToSpeechSettings) ProtoMessage() {}

func (x *TextToSpeechSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToSpeechSettings.ProtoReflect.Descriptor instead.
func (*TextToSpeechSettings) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{2}
}

func (x *TextToSpeechSettings) GetService() TextToSpeechService {
	if x != nil {
		return x.Service
	}
	return TextToSpeechService_GOOGLE
}

func (x *TextToSpeechSettings) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *TextToSpeechSettings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AmountTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min float64 `protobuf:"fixed64,1,opt,name=Min,proto3" json:"Min,omitempty"`
	Max float64 `protobuf:"fixed64,2,opt,name=Max,proto3" json:"Max,omitempty"`
}

func (x *AmountTrigger) Reset() {
	*x = AmountTrigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmountTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountTrigger) ProtoMessage() {}

func (x *AmountTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountTrigger.ProtoReflect.Descriptor instead.
func (*AmountTrigger) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{3}
}

func (x *AmountTrigger) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AmountTrigger) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Alert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type          AlertType             `protobuf:"varint,2,opt,name=Type,proto3,enum=stredono.AlertType" json:"Type,omitempty"`
	AmountTrigger *AmountTrigger        `protobuf:"bytes,3,opt,name=AmountTrigger,proto3,oneof" json:"AmountTrigger,omitempty"`
	Template      string                `protobuf:"bytes,4,opt,name=Template,proto3" json:"Template,omitempty"`
	Style         *AlertStyle           `protobuf:"bytes,5,opt,name=Style,proto3" json:"Style,omitempty"`
	TtsSettings   *TextToSpeechSettings `protobuf:"bytes,6,opt,name=TtsSettings,proto3,oneof" json:"TtsSettings,omitempty"`
}

func (x *Alert) Reset() {
	*x = Alert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{4}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_DONATE
}

func (x *Alert) GetAmountTrigger() *AmountTrigger {
	if x != nil {
		return x.AmountTrigger
	}
	return nil
}

func (x *Alert) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Alert) GetStyle() *AlertStyle {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *Alert) GetTtsSettings() *TextToSpeechSettings {
	if x != nil {
		return x.TtsSettings
	}
	return nil
}

type AlertStyle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GifUrl      string        `protobuf:"bytes,1,opt,name=GifUrl,proto3" json:"GifUrl,omitempty"`
	SoundUrl    string        `protobuf:"bytes,2,opt,name=SoundUrl,proto3" json:"SoundUrl,omitempty"`
	Animation   AnimationType `protobuf:"varint,3,opt,name=Animation,proto3,enum=stredono.AnimationType" json:"Animation,omitempty"`
	TextColor   string        `protobuf:"bytes,4,opt,name=TextColor,proto3" json:"TextColor,omitempty"`
	AccentColor string        `protobuf:"bytes,5,opt,name=AccentColor,proto3" json:"AccentColor,omitempty"`
}

func (x *AlertStyle) Reset() {
	*x = AlertStyle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertStyle) ProtoMessage() {}

func (x *AlertStyle) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertStyle.ProtoReflect.Descriptor instead.
func (*AlertStyle) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{5}
}

func (x *AlertStyle) GetGifUrl() string {
	if x != nil {
		return x.GifUrl
	}
	return ""
}

func (x *AlertStyle) GetSoundUrl() string {
	if x != nil {
		return x.SoundUrl
	}
	return ""
}

func (x *AlertStyle) GetAnimation() AnimationType {
	if x != nil {
		return x.Animation
	}
	return AnimationType_SHAKE
}

func (x *AlertStyle) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *AlertStyle) GetAccentColor() string {
	if x != nil {
		return x.AccentColor
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users    []string  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	Amounts  []float64 `protobuf:"fixed64,2,rep,packed,name=Amounts,proto3" json:"Amounts,omitempty"`
	Currency *string   `protobuf:"bytes,3,opt,name=Currency,proto3,oneof" json:"Currency,omitempty"`
	Message  *string   `protobuf:"bytes,4,opt,name=Message,proto3,oneof" json:"Message,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Event) GetAmounts() []float64 {
	if x != nil {
		return x.Amounts
	}
	return nil
}

func (x *Event) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Access  string `protobuf:"bytes,1,opt,name=Access,proto3" json:"Access,omitempty"`
	Refresh string `protobuf:"bytes,2,opt,name=Refresh,proto3" json:"Refresh,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stredono_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stredono_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_pb_stredono_proto_rawDescGZIP(), []int{7}
}

func (x *Token) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Token) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

var File_pb_stredono_proto protoreflect.FileDescriptor

var file_pb_stredono_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x22, 0x82, 0x02,
	0x0a, 0x03, 0x54, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f,
	0x6e, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f,
	0x6e, 0x6f, 0x2e, 0x54, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0xa9, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x24, 0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f,
	0x6e, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f,
	0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x06, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x22, 0x81,
	0x01, 0x0a, 0x14, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64,
	0x6f, 0x6e, 0x6f, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x22, 0x33, 0x0a, 0x0d, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x4d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x4d, 0x61, 0x78, 0x22, 0xb5, 0x02, 0x0a, 0x05, 0x41, 0x6c, 0x65, 0x72,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2e, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0d, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x53, 0x74,
	0x79, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72, 0x65,
	0x64, 0x6f, 0x6e, 0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52,
	0x05, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x54, 0x74, 0x73, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74,
	0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70, 0x65,
	0x65, 0x63, 0x68, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x01, 0x52, 0x0b, 0x54,
	0x74, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a,
	0x0e, 0x5f, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x54, 0x74, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0xb7, 0x01, 0x0a, 0x0a, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x47, 0x69, 0x66, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x47, 0x69, 0x66, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x55,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x55,
	0x72, 0x6c, 0x12, 0x35, 0x0a, 0x09, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f,
	0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x65, 0x78,
	0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x65,
	0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63,
	0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x90, 0x01, 0x0a, 0x05, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x2a, 0x2a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x42, 0x49, 0x54, 0x53, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4c,
	0x4e, 0x10, 0x02, 0x2a, 0x44, 0x0a, 0x09, 0x54, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x2a, 0x49, 0x0a, 0x09, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x4e, 0x41, 0x54, 0x45,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x42, 0x47, 0x49, 0x46, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x41,
	0x49, 0x44, 0x10, 0x04, 0x2a, 0x31, 0x0a, 0x13, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70,
	0x65, 0x65, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x47,
	0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x4c, 0x45, 0x56, 0x45,
	0x4e, 0x4c, 0x41, 0x42, 0x53, 0x10, 0x01, 0x2a, 0x26, 0x0a, 0x0d, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48, 0x41, 0x4b,
	0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x4f, 0x55, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x42,
	0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6b,
	0x75, 0x6c, 0x69, 0x6b, 0x30, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_stredono_proto_rawDescOnce sync.Once
	file_pb_stredono_proto_rawDescData = file_pb_stredono_proto_rawDesc
)

func file_pb_stredono_proto_rawDescGZIP() []byte {
	file_pb_stredono_proto_rawDescOnce.Do(func() {
		file_pb_stredono_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_stredono_proto_rawDescData)
	})
	return file_pb_stredono_proto_rawDescData
}

var file_pb_stredono_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pb_stredono_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_stredono_proto_goTypes = []interface{}{
	(Currency)(0),                // 0: stredono.Currency
	(TipStatus)(0),               // 1: stredono.TipStatus
	(AlertType)(0),               // 2: stredono.AlertType
	(TextToSpeechService)(0),     // 3: stredono.TextToSpeechService
	(AnimationType)(0),           // 4: stredono.AnimationType
	(*Tip)(nil),                  // 5: stredono.Tip
	(*User)(nil),                 // 6: stredono.User
	(*TextToSpeechSettings)(nil), // 7: stredono.TextToSpeechSettings
	(*AmountTrigger)(nil),        // 8: stredono.AmountTrigger
	(*Alert)(nil),                // 9: stredono.Alert
	(*AlertStyle)(nil),           // 10: stredono.AlertStyle
	(*Event)(nil),                // 11: stredono.Event
	(*Token)(nil),                // 12: stredono.Token
}
var file_pb_stredono_proto_depIdxs = []int32{
	0,  // 0: stredono.Tip.Currency:type_name -> stredono.Currency
	1,  // 1: stredono.Tip.Status:type_name -> stredono.TipStatus
	0,  // 2: stredono.User.Currency:type_name -> stredono.Currency
	9,  // 3: stredono.User.Alerts:type_name -> stredono.Alert
	3,  // 4: stredono.TextToSpeechSettings.Service:type_name -> stredono.TextToSpeechService
	2,  // 5: stredono.Alert.Type:type_name -> stredono.AlertType
	8,  // 6: stredono.Alert.AmountTrigger:type_name -> stredono.AmountTrigger
	10, // 7: stredono.Alert.Style:type_name -> stredono.AlertStyle
	7,  // 8: stredono.Alert.TtsSettings:type_name -> stredono.TextToSpeechSettings
	4,  // 9: stredono.AlertStyle.Animation:type_name -> stredono.AnimationType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pb_stredono_proto_init() }
func file_pb_stredono_proto_init() {
	if File_pb_stredono_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_stredono_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stredono_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stredono_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextToSpeechSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stredono_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AmountTrigger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stredono_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stredono_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertStyle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stredono_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stredono_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_stredono_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_pb_stredono_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_stredono_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_stredono_proto_goTypes,
		DependencyIndexes: file_pb_stredono_proto_depIdxs,
		EnumInfos:         file_pb_stredono_proto_enumTypes,
		MessageInfos:      file_pb_stredono_proto_msgTypes,
	}.Build()
	File_pb_stredono_proto = out.File
	file_pb_stredono_proto_rawDesc = nil
	file_pb_stredono_proto_goTypes = nil
	file_pb_stredono_proto_depIdxs = nil
}
