// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: pb/tip_settings.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthLevel int32

const (
	AuthLevel_NONE  AuthLevel = 0
	AuthLevel_EMAIL AuthLevel = 1
	AuthLevel_OIDC  AuthLevel = 2
)

// Enum value maps for AuthLevel.
var (
	AuthLevel_name = map[int32]string{
		0: "NONE",
		1: "EMAIL",
		2: "OIDC",
	}
	AuthLevel_value = map[string]int32{
		"NONE":  0,
		"EMAIL": 1,
		"OIDC":  2,
	}
)

func (x AuthLevel) Enum() *AuthLevel {
	p := new(AuthLevel)
	*p = x
	return p
}

func (x AuthLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_tip_settings_proto_enumTypes[0].Descriptor()
}

func (AuthLevel) Type() protoreflect.EnumType {
	return &file_pb_tip_settings_proto_enumTypes[0]
}

func (x AuthLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthLevel.Descriptor instead.
func (AuthLevel) EnumDescriptor() ([]byte, []int) {
	return file_pb_tip_settings_proto_rawDescGZIP(), []int{0}
}

type TipSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinAmount    float64   `protobuf:"fixed64,1,opt,name=MinAmount,proto3" json:"MinAmount,omitempty"`
	MinAuthLevel AuthLevel `protobuf:"varint,2,opt,name=MinAuthLevel,proto3,enum=stredono.AuthLevel" json:"MinAuthLevel,omitempty"`
	Currency     Currency  `protobuf:"varint,3,opt,name=Currency,proto3,enum=stredono.Currency" json:"Currency,omitempty"`
}

func (x *TipSettings) Reset() {
	*x = TipSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tip_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipSettings) ProtoMessage() {}

func (x *TipSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tip_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipSettings.ProtoReflect.Descriptor instead.
func (*TipSettings) Descriptor() ([]byte, []int) {
	return file_pb_tip_settings_proto_rawDescGZIP(), []int{0}
}

func (x *TipSettings) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *TipSettings) GetMinAuthLevel() AuthLevel {
	if x != nil {
		return x.MinAuthLevel
	}
	return AuthLevel_NONE
}

func (x *TipSettings) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_UNKNOWN
}

var File_pb_tip_settings_proto protoreflect.FileDescriptor

var file_pb_tip_settings_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x74, 0x69, 0x70, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e,
	0x6f, 0x1a, 0x0e, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x94, 0x01, 0x0a, 0x0b, 0x54, 0x69, 0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x37, 0x0a, 0x0c, 0x4d, 0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x64, 0x6f, 0x6e, 0x6f,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x0c, 0x4d, 0x69, 0x6e, 0x41,
	0x75, 0x74, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x72,
	0x65, 0x64, 0x6f, 0x6e, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2a, 0x2a, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x49,
	0x44, 0x43, 0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x75, 0x6c, 0x69, 0x6b, 0x30, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x64,
	0x6f, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_tip_settings_proto_rawDescOnce sync.Once
	file_pb_tip_settings_proto_rawDescData = file_pb_tip_settings_proto_rawDesc
)

func file_pb_tip_settings_proto_rawDescGZIP() []byte {
	file_pb_tip_settings_proto_rawDescOnce.Do(func() {
		file_pb_tip_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_tip_settings_proto_rawDescData)
	})
	return file_pb_tip_settings_proto_rawDescData
}

var file_pb_tip_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_tip_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_tip_settings_proto_goTypes = []interface{}{
	(AuthLevel)(0),      // 0: stredono.AuthLevel
	(*TipSettings)(nil), // 1: stredono.TipSettings
	(Currency)(0),       // 2: stredono.Currency
}
var file_pb_tip_settings_proto_depIdxs = []int32{
	0, // 0: stredono.TipSettings.MinAuthLevel:type_name -> stredono.AuthLevel
	2, // 1: stredono.TipSettings.Currency:type_name -> stredono.Currency
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_tip_settings_proto_init() }
func file_pb_tip_settings_proto_init() {
	if File_pb_tip_settings_proto != nil {
		return
	}
	file_pb_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_tip_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_tip_settings_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_tip_settings_proto_goTypes,
		DependencyIndexes: file_pb_tip_settings_proto_depIdxs,
		EnumInfos:         file_pb_tip_settings_proto_enumTypes,
		MessageInfos:      file_pb_tip_settings_proto_msgTypes,
	}.Build()
	File_pb_tip_settings_proto = out.File
	file_pb_tip_settings_proto_rawDesc = nil
	file_pb_tip_settings_proto_goTypes = nil
	file_pb_tip_settings_proto_depIdxs = nil
}
