name: 'Test and Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test Cloud Functions
        uses: ./.github/actions/go
        with:
          go-version: '1.22.x'
          src: 'functions'

  sveltekit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js v20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        shell: bash
        working-directory: app

      - name: Build static files
        run: npm build
        shell: bash
        working-directory: app

      - name: Test app
        run: npm test
        shell: bash
        working-directory: app

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sveltekit
          path: app/build

  deploy:
    needs: [go, sveltekit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        shell: bash

      - name: Download SvelteKit artifacts
        uses: actions/download-artifact@v3
        with:
          name: sveltekit
          path: app/build

      - uses: ./.github/actions/terraform
        with:
          dir: 'infra'