name: 'Test and Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test Cloud Functions
        uses: ./.github/actions/go
        with:
          go-version: '1.22'
          dir: 'functions'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Plan and Apply
        uses: ./.github/actions/terraform
        with:
          dir: 'infra'