name: 'Test and Deploy'

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        shell: bash

      - name: Build and Test Cloud Functions
        uses: ./.github/actions/go
        with:
          go-version: '1.22.x'
          working-dir: 'functions'

      - name: Test and Build SvelteKit
        uses: ./.github/actions/sveltekit
        with:
          node-version: '20.x'
          pnpm-version: '8.x'
          working-dir: 'app'

      - name: Get branch name
        id: get_branch
        uses: ./.github/actions/branch-name

      - uses: ./.github/actions/terraform
        with:
          working-dir: 'infra'
          workspace: ${{ steps.get_branch.outputs.branch }}