name: 'Test and Deploy'

on:
  push:
  pull_request:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Name
        run: echo "Running on branch ${{ env.BRANCH_NAME }}"
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        shell: bash

      - name: Build and Test Cloud Functions
        uses: ./.github/actions/go
        with:
          go-version: '1.22.x'
          working-dir: 'functions'

      - name: Deploy Infrastructure
        uses: ./.github/actions/terraform
        with:
          working-dir: 'infra'
          branch: ${{ env.BRANCH_NAME }}

      - name: Test and Build SvelteKit
        uses: ./.github/actions/sveltekit
        with:
          node-version: '20.x'
          pnpm-version: '8.x'
          working-dir: 'app'

      - name: Deploy Firebase Hosting
        run: firebase deploy --only hosting
        working-directory: app